### ISSUE TITLE
Poor results

### ISSUE THREAD

**Issue by xin-xinhanggao** [bamos/dcgan-completion.tensorflow#11]
I am sorry to bother you, but I meet the problem same as the previous participators.
![before](https://cloud.githubusercontent.com/assets/20569510/21080311/bfe8f8ca-bfe6-11e6-94d3-d131eadf33c2.png)
I test the first 4 images of celebA, but after 4100 iters I just can get this
![4100](https://cloud.githubusercontent.com/assets/20569510/21080318/dea7f46e-bfe6-11e6-86dc-fa9f097455c4.png)
I use the checkout file you provide, and the lr 0.0001 momentum 0.9 lam=0.1

The log of loss is here:
(0, 5438.4629)
(50, 2176.6125)
(100, 1832.1901)
(150, 1647.3655)
(200, 1559.5751)
(250, 1565.9722)
(300, 1507.9558)
(350, 1586.2904)
(400, 1487.1926)
(450, 1490.8186)
(500, 1456.236)
(550, 1440.8938)
(600, 1424.374)
(650, 1498.3505)
(700, 1465.35)
(750, 1462.46)
(800, 1405.9574)
(850, 1421.2158)
(900, 1497.1049)
(950, 1448.3206)
(1000, 1482.5293)
(1050, 1445.6565)
(1100, 1425.0696)
(1150, 1528.2311)
(1200, 1545.6395)
(1250, 1394.381)
(1300, 1532.6442)
(1350, 1491.2181)
(1400, 1401.6718)
(1450, 1382.696)
(1500, 1414.021)
(1550, 1593.165)
(1600, 1423.8958)
(1650, 1464.3767)
(1700, 1390.084)
(1750, 1476.6337)
(1800, 1416.7273)
(1850, 1529.7141)
(1900, 1451.7915)
(1950, 1529.489)
(2000, 1481.5079)
(2050, 1436.3569)
(2100, 1358.0055)
(2150, 1358.7209)
(2200, 1506.1733)
(2250, 1393.1555)
(2300, 1408.2441)
(2350, 1483.0356)
(2400, 1377.6108)
(2450, 1516.509)
(2500, 1486.5796)
(2550, 1420.6681)
(2600, 1368.9692)
(2650, 1395.9053)
(2700, 1456.8112)
(2750, 1511.428)
(2800, 1358.7203)
(2850, 1498.2517)
(2900, 1416.1931)
(2950, 1419.6449)
(3000, 1402.9338)
(3050, 1506.2152)
(3100, 1469.8186)
(3150, 1427.0465)
(3200, 1401.9683)
(3250, 1452.6249)
(3300, 1466.2008)
(3350, 1347.4689)
(3400, 1382.7289)
(3450, 1494.2131)
(3500, 1429.3224)
(3550, 1384.4293)
(3600, 1468.8229)
(3650, 1356.1833)
(3700, 1413.0737)
(3750, 1358.0089)
(3800, 1429.6335)
(3850, 1473.816)
(3900, 1482.1053)
(3950, 1367.022)
(4000, 1408.011)
(4050, 1411.2065)
(4100, 1369.4713)

**Comment by bamos** [comment]
Hi, those images don't look aligned, can you try running the OpenFace alignment code on your images first? Also, I think the results will be better with ADAM instead of GD. Please post in issue #9 if you implement this.

-Brandon.
