### ISSUE TITLE
error with tf 0.12

### ISSUE THREAD

**Issue by kursatozdalli** [bamos/dcgan-completion.tensorflow#14]
ValueError: Variable discriminator/d_bn1/discriminator_1/d_bn1/discriminator_1/d_bn1/moments/moments_1/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by ghost** [comment]
I'm new to tensorflow, don't trust myself to fix this, but found this issue post for ema

https://github.com/tensorflow/tensorflow/issues/5827

**Comment by berleant** [comment]
I'm getting this too. Also new, but I'll give it a shot. Nothing like learning by doing, eh?

**Comment by bamos** [comment]
I've updated to TF >=1.0
