### ISSUE TITLE
sorry i don't know how to start a new train

### ISSUE THREAD

**Issue by lavalse** [bamos/dcgan-completion.tensorflow#15]
i delete the checkpoint directory and use code:
./train-dcgan.py --dataset ./data/your-dataset/aligned --epoch 20

but everytime it tells me:
"An existing model was not found in the checkpoint directory. Initializing a new one"

but how to start to train a new one?  or how to initializing a new one?

can you help me?

**Comment by bamos** [comment]
Hi, you can delete the checkpoint directory to train a new model.

**Comment by lavalse** [comment]
OH i know what the problem it is , thanks very much

**Comment by eastsky0614** [comment]
I have a same problem with you. I already delete checkpoint folder or file. But, It doen't work.
How can you solve that problem?

**Comment by qiuxiaqing** [comment]
@lavalse I meet the same problem when i training the model，how do you solve this problem? Thanks a lot
