### ISSUE TITLE
Adapt the code for custom input format (different input size / channels)

### ISSUE THREAD

**Issue by mgarbade** [bamos/dcgan-completion.tensorflow#19]
First of all. Thanks a lot for sharing your code!

Do you have a suggestion which parts of the code I would need to adapt in order to make it work with 1-channel images that are larger than 64x64 pixels.
I tried to just change the `image_size` parameter, but that produces an error, unless I set the `is_crop` parameter to `True`, but that again would reduce the input size to 64x64.

I assume that I have to modify the `get_image` function?

```
def imread(path,c_dim):
    if c_dim == 3:
        im  = scipy.misc.imread(path, mode='RGB').astype(np.float)
    elif c_dim == 1:
        im  = scipy.misc.imread(path, mode='L').astype(np.float)
    else:
        print('Error: c_dim must be either 3 or 1')
            
    return im
```

but it still gives me an error:

`ValueError: Cannot feed value of shape (64, 64, 128) for Tensor u'gt_labels:0', which has shape '(?, 64, 128, 1)'`

Maybe I  need to add a singleton dimension for the channels...

**Comment by mgarbade** [comment]
Ok, let's say it wasn't super hard :D.

```
def imread(path,c_dim):
    if c_dim == 3:
        im  = scipy.misc.imread(path, mode='RGB').astype(np.float)
    elif c_dim == 1:
        im  = scipy.misc.imread(path, mode='L').astype(np.float)
        im = np.expand_dims(im, 3)
    else:
        print('Error: c_dim must be either 3 or 1')
            
    return im
```

Sorry for the spamming ;)

**Comment by bamos** [comment]
:) Glad you figured it out.

-Brandon.

**Comment by kplettl** [comment]
@mgarbade do you mind sharing how you were able to make the network work for 1 channel images? I'm new to tensorflow. I have made the modification to the imread function as you suggested but I still get an error about reshaping: 
InvalidArgumentError: Cannot reshape a tensor with 786432 elements to shape [64,8,8,8,8,1] (262144 elements) for 'Reshape_1' (op: 'Reshape') with input shapes: [64,64,64,3], [6] and with input tensors computed as partial shapes: input[1] = [64,8,8,8,8,1].

Any advice you can offer would be wonderful!! Thanks!
