### ISSUE TITLE
makedirs() got an unexpected keyword argument 'exist_ok

### ISSUE THREAD

**Issue by yaserali542** [bamos/dcgan-completion.tensorflow#20]
Hi I have completed the training process, but for the complete.py file I got this Error

File "./complete.py", line 35, in <module>
    dcgan.complete(args)
  File "/home/mohammed/dcgan-completion.tensorflow/model.py", line 220, in complete
    os.makedirs(os.path.join(config.outDir, 'hats_imgs'), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

Help me out Please. Thanks

**Comment by Wedjaa** [comment]
@yaserali542 This code is for python 3 - if you're getting that error it means you are running python 2. Check with `python -V` to see which version you are running. If you have both versions of python on your system.

**Comment by zoraZHJ** [comment]
caused by the python version 2.x, change it to
        if not os.path.exists(os.path.join(config.outDir, 'hats_imgs')):
            os.makedirs(os.path.join(config.outDir, 'hats_imgs'))
or use the python 3.x

**Comment by azainab** [comment]
This error occurs if you are running python2 you can just remove the keyword exist_ok and it will work fine.

For example: 
![image](https://cloud.githubusercontent.com/assets/25388406/26673196/b2f77776-46c4-11e7-8593-941fae411dfb.png)
can be made as 
![image](https://cloud.githubusercontent.com/assets/25388406/26673208/be2f9092-46c4-11e7-9747-d2ffbdcb7c11.png)

**Comment by Robotatron** [comment]
Using python3 and still have this error

**Comment by MoeNeuron** [comment]
> Using python3 and still have this error

Are you sure you imported right?
```python
from pathlib import Path
```
