### ISSUE TITLE
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

### ISSUE THREAD

**Issue by xycyx** [bamos/dcgan-completion.tensorflow#32]
I got this error when training the model with tensorflow 1.1.0
Seems that this issue related to tf r1.0
I'm a beginner of tensorflow, could you give me some suggestions to fix this issue?

**Comment by xycyx** [comment]
I've found a solution and submitted a pull request to solve these issues.
#https://github.com/carpedm20/DCGAN-tensorflow/commit/6c2a0ca5241eed7c83b7c38c0e46450b9a77fc3d

**Comment by bamos** [comment]
Thanks! I've merged in your PR.
