### ISSUE TITLE
Have you implment the poisson blending in this part?

### ISSUE THREAD

**Issue by k0286** [bamos/dcgan-completion.tensorflow#50]
Hello, 

I'm a newcomer of DCGAN.

Because I can not understand how to use poisson blending in this situation when I read Yeh's paper.

I notice that you also describe to use poisson blending to smooth the reconstructed image in your article.

I think that reviewing this project may help me, but I'm not sure which parts in this project are used to implement poisson blending.

many thanks

Regards

**Comment by bamos** [comment]
Hi, I haven't implemented poisson blending in this repo.

-Brandon.
