### ISSUE TITLE
In the model.py, line 420, dimension is different with the one in original paper

### ISSUE THREAD

**Issue by waterdeepmage** [bamos/dcgan-completion.tensorflow#53]
Hi, Bamos,

In the line 420 of model.py code, self.z_, self.h0_w, self.h0_b = linear(z, self.gf_dim * 8 * 4 * 4, 'g_h0_lin', with_w=True)

self.gf_dim is 64, thus, the dimension of the output should be 64 * 8 * 4 * 4, which is 512 * 4 * 4. In the DCGAN paper the first layer should be 1024  * 4 * 4. Is there a reason for you to change it as 512 from 1024?

Thanks

**Comment by bamos** [comment]
Hi, I'm not sure. I think that part is from Taehoon Kim's original dcgan repo.
