### ISSUE TITLE
 Can not reproduce such a good effect

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [bamos/dcgan-completion.tensorflow#7]
I used celebA which had 200K face pictures as the trainable database.
Firstly I cropped and aligned them ,and resized to 64*64.
Although i followed this blog :

>  http://bamos.github.io/2016/08/09/deep-completion

 and used 15  ,20 and  25 epochs respectively ,but my inpainting effect was worse 。

**Comment by bamos** [comment]
Hi @xuyifeng-nwpu - it's difficult to say what's going on since you trained the GAN with a different dataset. My pre-trained model is available in this repo if you want to use that instead.

-Brandon.
