### ISSUE TITLE
Disappointing result for the demo with 3 images.

### ISSUE THREAD

**Issue by benstaf** [bamos/dcgan-completion.tensorflow#8]
I ran the demo from your blog post with 3 images, but the result is disppointing:

![completion_problem](https://cloud.githubusercontent.com/assets/8183572/20307614/f31e6e3a-ab48-11e6-8916-88f19ebda52a.gif)

My input images are:
![face3](https://cloud.githubusercontent.com/assets/8183572/20307767/a7305a46-ab49-11e6-9886-ef64f060e320.jpg)
![face2](https://cloud.githubusercontent.com/assets/8183572/20307768/a73328a2-ab49-11e6-953a-b940f89b3b90.jpg)
![obama](https://cloud.githubusercontent.com/assets/8183572/20307769/a735fe4c-ab49-11e6-9d4e-5d1dc4ce1e5a.jpg)

I did not re-trained the model, I directly ran the code:

`./openface/util/align-dlib.py data/dcgan-completion.tensorflow/data/your-dataset/raw align innerEyesAndBottomLip data/dcgan-completion.tensorflow/data/your-dataset/aligned --size 64`

`./complete.py ./data/your-test-data/aligned/* --outDir outputImages`

`cd outputImages
convert -delay 10 -loop 0 completed/*.png completion.gif`

**Comment by bamos** [comment]
Hi, I'm not sure what's going on with the first image but near the end the second two look reasonable. Using an adaptive optimization technique could make the optimization more stable and I just opened issue #9 if anybody's interested in implementing this, it should just be a few lines of code. It's described in [Algorithm 1 of this paper](https://arxiv.org/abs/1412.6980) and there are plenty of references of how to implement it in Python, and I like using the [Torch implementation for reference](https://github.com/torch/optim/blob/master/adam.lua).

-Brandon.

**Comment by benstaf** [comment]
The first image is computer-generated 

![](https://cloud.githubusercontent.com/assets/8183572/20307768/a73328a2-ab49-11e6-953a-b940f89b3b90.jpg)

The other two are more 'natural'. So this image can fool humans into seeing a face, but not the GAN. Can you explain why?
